swagger: "2.0"
info:
  version: "1.0.0"
  title: "Shikshalokam: Assessment"
  description: Evaluation Platform
  termsOfService: https://dev.shikshalokam.org/
  contact:
    name: Shikshalokam API team
    email: foo@example.com
    url: https://dev.shikshalokam.org/
  license:
    name: MIT
    url: http://opensource.org/licenses/MIT
host: https://dev.shikshalokam.org/
basePath: /assessment/api/v1/
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json
